export const OurWorkData = [
    {
        id: 1,
        name: "Global Corporates",
        imgSrc: "Corporate_Business_Events",
        textOne: `Industry: Corporate & Business`,
        textTwo: `Services Provided: Ultra Fine LED Video Walls, Digital Wireless Audio, Hybrid Streaming & Broadcast, Modular Staging`,
        textThree: `The Challenge: Deliver flawless presentation optics and zerolatency international webcasting for over 800 inperson executives and thousands of remote attendees.`,
        textFour: `The Solution: Deployed a high contrast 4K LED backdrop with seamless multi input switching, custom acoustic line arrays tailored to the venue's reflective architecture, and dedicated redundant internet lines for glitch free live streaming.`,
        textFive: `The Result: Crystal clear speech delivery and uninterrupted global broadcast coverage across all three days.`,
    },
    {
        id: 2,
        name: "Dvido Entertainment",
        imgSrc: "Entertainment_Live_Shows",
        textOne: `Industry: Entertainment & Live Shows`,
        textTwo: `Services Provided: Festival Grade Line Array Sound, Intelligent Moving Lighting, Certified Heavy Duty Rigging, Modular Outdoor Staging`,
        textThree: `The Challenge: Build a high capacity main stage capable of hosting multiple headline performers, delivering deep, high SPL audio coverage across a 5,000 person outdoor crowd.`,
        textFour: `The Solution: Engineered a fully rigged roof trussing system with ETCP compliant safety specs, suspended dual line array hangs with cardiod subwoofers for controlled bass dispersion, and programmed dynamic DMX lighting shows tailored to each artist's set.`,
        textFive: `The Result: An immersive, high impact festival experience with optimal sound levels and zero structural or technical delays.`,
    },
    {
        id: 3,
        name: "WoodLands Exhibits",
        imgSrc: "Exhibitions_Trade_Shows",
        textOne: `Industry: Exhibitions & Trade Shows`,
        textTwo: `Services Provided: Custom Truss Structures, Branded Graphics, Directional Accent Lighting, Digital Signage Displays`,
        textThree: `The Challenge: Transform an empty exhibition hall into a multibooth commercial floor with clear sightlines, functional ambient lighting, and high impact branding for over 40 exhibitors.`,
        textFour: `The Solution: Constructed a series of overhead modular truss grids with integrated spotlighting to highlight key sponsor zones, paired with high brightness digital signage displays for realtime schedule updates and brand ads.`,
        textFive: `The Result: Enhanced foot traffic for exhibitors, clear venue navigation, and a modern, professional exhibition atmosphere.`,
    },
    {
        id: 4,
        name: "Zara & Retailers Lunch ",
        imgSrc: "Retail_Brand_Experiences",
        textOne: `Industry: Retail & Brand Experiences`,
        textTwo: `Services Provided: Curved LED Displays, Architectural Uplighting, Custom Print Graphics, Interactive Audio`,
        textThree: `The Challenge: Create an intimate, visually striking environment inside a retail venue to unveil a new product line to media and influencers.`,
        textFour: `The Solution: Installed a custom curved LED video wall to wrap around the central display area, synchronized with custom architectural LED uplighting and high fidelity ambient background audio.`,
        textFive: `The Result: A photogenic, highly engaging sensory experience that generated massive social media coverage and press pickup.`,
    },
    {
        id: 5,
        name: "Religion As One",
        imgSrc: "Religious_Institutions",
        textOne: `Industry: Religious Institutions`,
        textTwo: `Services Provided: Feedback Free Wireless Mic Systems, Acoustic Line Arrays, High Contrast Projection Screens, Multi Camera Stream Setup`,
        textThree: `The Challenge: Eliminate acoustic reverberation and audio feedback in a high ceiling sanctuary while broadcasting live services to thousands of online worshipers.`,
        textFour: `The Solution: Configured targeted digital line arrays for controlled acoustic coverage, installed high lumen projection systems for live worship lyrics, and integrated multi camera broadcast switchers.`,
        textFive: `The Result: Warm, crystal clear speech and music delivery across the main auditorium with seamless high definition streaming for remote congregants.`,
    },
    {
        id: 6,
        name: "Savora Hotels Springs",
        imgSrc: "Hospitality_Tourism",
        textOne: `Industry: Hospitality & Tourism`,
        textTwo: `Services Provided: Ambient Architectural Lighting, Low Profile Audio Arrays, Custom Stage Wraps, Outdoor Festoon Lighting`,
        textThree: `The Challenge: Deliver high end AV and atmospheric lighting for an outdoor resort gala without disrupting the venue's luxury visual aesthetics.`,
        textFour: `The Solution: Deployed wireless battery powered LED uplights, low profile custom wrapped speakers that blended into the venue backdrop, and soft festoon lighting across open air garden spaces.`,
        textFive: `The Result: An elegant, visually unobtrusive installation that enhanced the resort environment and provided exceptional audio visual coverage.`,
    },
    {
        id: 7,
        name: "Mentality Clinics Convention",
        imgSrc: "Healthcare_Medical",
        textOne: `Industry: Healthcare & Medical`,
        textTwo: `Services Provided: High Resolution 4K Presentation Displays, Precision Panel Microphones, Secure Webcasting, Digital Podium Systems`,
        textThree: `The Challenge: Provide ultra clear display optics for detailed medical slide presentations and precise panel audio for complex Q&A sessions.`,
        textFour: `The Solution: Supplied ultra high definition 4K screens for intricate visual rendering, goose neck panel mics with active noise gating, and encrypted livestreaming feeds for remote medical delegates.`,
        textFive: `The Result: Flawless visual clarity for medical demonstrations and total technical precision across all keynote and breakout sessions.`,
    },
    {
        id: 8,
        name: "Governemnt Parastals Gathering",
        imgSrc: "Government_Public_Sector",
        textOne: `Industry: Government & Public Sector`,
        textTwo: `Services Provided: High Capacity Outdoor PA Systems, Protocol Compliant Stage Staging, Redundant Power Systems, Secure Audio Feeds`,
        textThree: `The Challenge: Host a large scale public civic gathering requiring strict protocol adherence, zero downtime audio reliability, and wide coverage across a large outdoor venue.`,
        textFour: `The Solution: Erected heavy duty staging with safety guardrails, deployed high capacity outdoor line array hangs with generator backup systems, and split multi channel audio feeds for press media distribution.`,
        textFive: `The Result: Dependable, high volume audio coverage across the entire grounds with strict adherence to official state protocol and press compliance.`,
    },
    {
        id: 9,
        name: "Pretoria Learnings",
        imgSrc: "Education_Training",
        textOne: `Industry: Education & Training`,
        textTwo: `Services Provided: MultiZone Public Address Systems, High Brightness Projection, Interactive Presentation Tools, Wireless Lapel Microphones`,
        textThree: `The Challenge: Outfit a multihall academic symposium with clear speech amplification and interactive presentation tools for simultaneous lectures.`,
        textFour: `The Solution: Installed independent multizone sound systems in each lecture hall, high brightness projection units for daylight viewing, and multichannel wireless mic systems for seamless speaker transitions.`,
        textFive: `The Result: Excellent acoustic intelligibility for academic presentations and effortless coordination across multiple concurrent training rooms.`,
    },
];